# fly.toml app configuration file generated for cold-wildflower-8620 on 2023-05-28T17:27:55-10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-wildflower-8620"
primary_region = "lax"

[env]
  PORT = "8080" # add this
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
